server:
  port: 8010

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  security:
    user:
      name: admin
      password: admin
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: baocms-discovery
      label: master
      profile: ${spring.profiles.active}
      username: admin
      password: admin
#      uri: http://admin:admin@localhost:8080
    inetutils:
      ignoredInterfaces:
      - docker0
      - veth.*
      preferredNetworks:
      - 192.168
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
